# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 128670af2dc56bf6fdcf8e4f26984c1faf2967a012fce3ae2de48726380a0fa932e4344ae96daee9fdd9523ad610fa74d65ec9295068a38850081a6204bf3a16

test:
  secret_key_base: 753ac81bc6961f409c04cddc974a53aeb4ca756f2f86863772de8438f605992e8509834fadb51f246cc6f0aa734fe98d6c5ba9d7b499f4a874f8693b25cb72d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
